### ISSUE TITLE
Global random_seed

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#22]
Can we define one random_seed in the top level of the configuration, that will be used everywhere?

**Comment by jindrahelcl** [comment]
`random_seed` should be first removed from the constructor of the vocabulary. The initializer of the random module should be called from the main function right at the start. This will be simple as soon as we introduce the changes in #73.

**Comment by jindrahelcl** [comment]
That's actually false... The random seed should be defined before the graph is built and before the TF random initializers are used (**not** just before the session is created). @obo seems to be working on this now. ?

**Comment by jindrahelcl** [comment]
Solved in #157

**Comment by tomasmcz** [comment]
Well, it is not. We're still unable to set the seed in configuration (useful eg. if I want to test the variance with different random seeds).
